[pytest]
addopts = [
    "-n=auto", 
    "--import-mode=importlib", 
    "--cov=shadertools", 
    "--cov=tests", 
    "--cov-report=term-missing", 
    "--cov-report=xml",
    "--junit-xml=test-report.xml"
]
testpaths = ["tests"]